=== humanendurance/SAP-CPI/Scenario/Job Application/ProfileParser.xsd
<!-- File		: ProfileParser.xsd  -->
<!-- Author		: Yeswanth Manikanta -->
<!-- Last Updated	: 20-Aug-2024	     -->	



<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
<!-- Uncomment the following line when using with an XML Validator -->
<!-- xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com" -->>

<xs:element name="profiles">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="candidate" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="firstName" type="xs:string" />
						<xs:element name="lastName" type="xs:string" />
						<xs:element name="gender" >
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value = "Male" />
									<xs:enumeration value = "Female" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="country" type="xs:string" />
						<xs:element name="skills" type="skills" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:complexType name="skills">
	<xs:sequence>
	<xs:element name="skillName" type="xs:string" />
	<xs:element name="skillCategory">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Programmer" />
				<xs:enumeration value="Software Developer" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="skillProficiency">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Noob" />
				<xs:enumeration value="Amateur" />
				<xs:enumeration value="Expert" />
				<xs:enumeration value="Seasoned" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	</xs:sequence>
</xs:complexType>
</xs:schema>

=== humanendurance/SAP-CPI/Scenario/Job Application/ProfileData.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- <profiles xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com ProfileParser.xsd"> -->
<profiles>
	<candidate>
		<firstName>Steve</firstName>
		<lastName>Martin</lastName>
		<gender>Male</gender>
		<country>India</country>
		<skills>
			<skillName>C++</skillName>
			<skillCategory>Programmer</skillCategory>
			<skillProficiency>Amateur</skillProficiency>
		</skills>
		<skills>
			<skillName>C</skillName>
			<skillCategory>Software Developer</skillCategory>
			<skillProficiency>Expert</skillProficiency>
		</skills>
	</candidate>
	
	<candidate>
		<firstName>Terry</firstName>
		<lastName>Davis</lastName>
		<gender>Male</gender>
		<country>USA</country>
		<skills>
			<skillName>C</skillName>
			<skillCategory>Software Developer</skillCategory>
			<skillProficiency>Seasoned</skillProficiency>
		</skills>
		<skills>
			<skillName>Holy C</skillName>
			<skillCategory>Software Developer</skillCategory>
			<skillProficiency>Seasoned</skillProficiency>
		</skills>
	</candidate>
	
	<candidate>
		<firstName>Srinivas</firstName>
		<lastName>Nithya</lastName>
		<gender>Female</gender>
		<country>Germany</country>
		<skills>
			<skillName>Python</skillName>
			<skillCategory>Programmer</skillCategory>
			<skillProficiency>Amateur</skillProficiency>
		</skills>
		<skills>
			<skillName>Java</skillName>
			<skillCategory>Software Developer</skillCategory>
			<skillProficiency>Amateur</skillProficiency>
		</skills>
		<skills>
			<skillName>Clojure</skillName>
			<skillCategory>Software Developer</skillCategory>
			<skillProficiency>Expert</skillProficiency>
		</skills>
		<skills>
			<skillName>Linux Shell</skillName>
			<skillCategory>Programmer</skillCategory>
			<skillProficiency>Amateur</skillProficiency>
		</skills>
	</candidate>
	
	<candidate>
		<firstName>Pramod</firstName>
		<lastName>Paramanandham</lastName>
		<gender>Male</gender>
		<country>UK</country>
		<skills>
			<skillName>CSS</skillName>
			<skillCategory>Programmer</skillCategory>
			<skillProficiency>Amateur</skillProficiency>
		</skills>
		<skills>
			<skillName>HTML</skillName>
			<skillCategory>Programmer</skillCategory>
			<skillProficiency>Amateur</skillProficiency>
		</skills>
		<skills>
			<skillName>JS-FrontEnd</skillName>
			<skillCategory>Programmer</skillCategory>
			<skillProficiency>Expert</skillProficiency>
		</skills>
	</candidate>

</profiles>
